### ISSUE TITLE
Problem with wording in Figure 9

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/EnvMutationalShiftsPaper#20]
@jbloom: I also found a problem with the wording in Figure 9. I wrote the the color scale ranges between "−6 < log10 𝑄 < 6". This is true for the *directional* log10 𝑄 values that account for omega being greater than or less than one, but not the raw log10 𝑄 values.

This is just a reminder for one of us to change this before re-submitting.

**Comment by jbloom** [comment]
I just got rid of this wording all together. I think it's fine just to say that sites are colored based on the strength of evidence and not go into details about exactly how the mapping is done from Q value to color, since people can't really judge color scales quantitatively be eye anyway and there is no scale bar. So the new wording in the last commit I pushed got rid of this language anyway.

All the numerical values are in Figure 9 - source data 1 anyway, so this is fine and not misleading.
